# Generated by Django 2.2.8 on 2020-02-22 07:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorInf',
            fields=[
                ('DoctorID', models.CharField(max_length=9, primary_key=True, serialize=False, unique=True)),
                ('Name', models.CharField(max_length=30)),
                ('Sex', models.CharField(max_length=2)),
                ('Age', models.IntegerField()),
                ('Photo', models.ImageField(default='None', upload_to='media')),
                ('Tel', models.CharField(max_length=11)),
                ('Position', models.CharField(max_length=20)),
                ('Office', models.CharField(max_length=20)),
                ('OfficeSite', models.CharField(max_length=20)),
                ('WorkTime', models.CharField(max_length=11)),
                ('Education', models.CharField(default='None', max_length=20)),
                ('Introduce', models.TextField(default='None')),
                ('Achievements', models.TextField(default='None')),
                ('Characters', models.TextField(default='None')),
                ('Category', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='DrugInf',
            fields=[
                ('DrugID', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('DrugName', models.CharField(max_length=20)),
                ('DeliveryUnit', models.CharField(max_length=10)),
                ('ProduceTime', models.DateField(default=django.utils.timezone.now)),
                ('EffectiveTime', models.IntegerField()),
                ('RetailPrice', models.FloatField()),
                ('WholesalePrice', models.FloatField()),
                ('DurgPurPrice', models.FloatField()),
                ('DrugNum', models.IntegerField()),
                ('Component', models.TextField(default='none')),
                ('Character', models.TextField(default='none')),
                ('Indication', models.TextField(default='none')),
                ('Specs', models.TextField(default='none')),
                ('Usage', models.TextField(default='none')),
                ('SideEffect', models.TextField(default='none')),
                ('Taboo', models.TextField(default='none')),
                ('Note', models.TextField(default='none')),
                ('Gravida', models.TextField(default='none')),
                ('ChildDrug', models.TextField(default='none')),
                ('OlderDrug', models.TextField(default='none')),
                ('DrugInteraction', models.TextField(default='none')),
                ('DrugOverdose', models.TextField(default='none')),
                ('DurgToxicology', models.TextField(default='none')),
                ('Store', models.TextField(default='none')),
                ('Packing', models.TextField(default='none')),
                ('ExecutiveStard', models.TextField(default='none')),
                ('Flag', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='StockInf',
            fields=[
                ('StockID', models.CharField(max_length=11, primary_key=True, serialize=False, unique=True)),
                ('StockType', models.CharField(max_length=8)),
                ('StockTime', models.DateField(default=django.utils.timezone.now)),
                ('DeliveryUnit', models.CharField(max_length=10)),
                ('InvoiceID', models.CharField(max_length=11)),
                ('InvoiceTime', models.DateField(default=django.utils.timezone.now)),
                ('DrugID', models.CharField(max_length=5)),
                ('DrugName', models.CharField(max_length=20)),
                ('Origin', models.CharField(max_length=20)),
                ('WholesalePrice', models.FloatField()),
                ('RetailPrice', models.FloatField()),
                ('DrugPurPrice', models.FloatField()),
                ('DrugNum', models.IntegerField()),
                ('PurchaseSum', models.FloatField()),
                ('EffectiveTime', models.IntegerField()),
                ('ProduceTime', models.DateField()),
                ('Remark', models.TextField(default='None')),
            ],
        ),
    ]
