# Generated by Django 2.2.8 on 2020-02-22 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InfManage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerInf',
            fields=[
                ('UserName', models.CharField(max_length=9, primary_key=True, serialize=False, unique=True)),
                ('PassWord', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
    ]
