# Generated by Django 2.2.8 on 2020-02-22 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InfManage', '0002_managerinf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockinf',
            old_name='StockTime',
            new_name='StockInTime',
        ),
        migrations.RenameField(
            model_name='stockinf',
            old_name='StockType',
            new_name='StockInType',
        ),
    ]
