# Generated by Django 2.2.8 on 2020-02-22 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InfManage', '0003_auto_20200222_2039'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StockInf',
            new_name='StockInInf',
        ),
        migrations.RenameField(
            model_name='stockininf',
            old_name='StockID',
            new_name='StockInID',
        ),
    ]
