# Generated by Django 2.2.8 on 2020-02-22 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InfManage', '0004_auto_20200222_2044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='druginf',
            old_name='ProduceTime',
            new_name='ProduceDate',
        ),
        migrations.RenameField(
            model_name='stockininf',
            old_name='ProduceTime',
            new_name='ProduceDate',
        ),
        migrations.RenameField(
            model_name='stockininf',
            old_name='StockInTime',
            new_name='StockInDate',
        ),
    ]
