# Generated by Django 2.2.8 on 2020-02-25 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InfManage', '0006_auto_20200224_1536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='druginf',
            old_name='DurgPurPrice',
            new_name='DrugPurPrice',
        ),
    ]
