# Generated by Django 2.2.8 on 2020-02-25 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InfManage', '0007_auto_20200225_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='druginf',
            name='DeliveryUnit',
            field=models.CharField(max_length=20),
        ),
    ]
