# Generated by Django 2.2.8 on 2020-02-27 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InfManage', '0008_auto_20200225_2102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caseinf',
            old_name='PetWeigth',
            new_name='PetWeight',
        ),
    ]
