# Generated by Django 2.2.8 on 2020-02-27 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InfManage', '0009_auto_20200227_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseinf',
            name='DoctorID',
            field=models.CharField(max_length=9),
        ),
    ]
