# Generated by Django 2.2.8 on 2020-03-15 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InfManage', '0010_auto_20200227_2345'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ManagerInf',
        ),
    ]
