# Generated by Django 2.2.8 on 2020-03-21 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InfManage', '0012_managerinf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseinf',
            name='CaseID',
            field=models.CharField(max_length=12, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='stockininf',
            name='InvoiceID',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='stockininf',
            name='StockInID',
            field=models.CharField(max_length=12, primary_key=True, serialize=False, unique=True),
        ),
    ]
