# Generated by Django 2.2.8 on 2020-03-21 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InfManage', '0014_auto_20200321_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockininf',
            name='DeliveryUnit',
            field=models.CharField(max_length=20),
        ),
    ]
