# Generated by Django 2.2.8 on 2020-04-11 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InfManage', '0015_auto_20200321_1824'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockininf',
            old_name='InvoiceTime',
            new_name='InvoiceDate',
        ),
    ]
