# Generated by Django 2.2.8 on 2020-04-14 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InfManage', '0021_auto_20200414_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorinf',
            name='Photo',
            field=models.ImageField(default='None', upload_to=''),
        ),
    ]
